### ISSUE TITLE
Relative paths to internal data

### ISSUE THREAD

**Issue by owiecc** [Alistairj43/TPMS-Designer#6]
The paths e.g. to `data\lattices\BCC.txt` are relative in the app code. The files cannot be loaded if the paths are not correctly set up in MATLAB. I believe they should be made relative to the App base folder.

**Comment by Alistairj43** [comment]
This is a good point. The current code relies on the person using this folder as their home directory.

I am not that familiar with the best way of doing this - do you have a suggestion of how to do this.
